name: build-ios-app
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm run init
      - run: fastlane match
        working-directory: ./ios
        # env:
        #   MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      - run: fastlane beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        working-directory: ./ios